### ISSUE TITLE
vue-cli@1.x中webpack配置问题

### ISSUE THREAD

**Issue by LDWX** [vuejs/vue-docs-zh-cn#10]
我之前一直用的是vue-cli@1.x。在实际开发过程中发现经常需要对webpack中的一些配置进行修改。比如说：修改生产环境的静态资源路径，修改多页面入口等。

我下文档中看到可以通过配置链的方式进行webpack配置。我想问一下，对于项目中原本已有的配置，在我加入相同配置项进入配置链后，会直接将默认配置替换吗？

因为我对webpack也不是特别熟悉，所以还没有做尝试。

**Comment by Jinjiang** [comment]
如果我理解正确的话，你指的“配置链”是通过 webpack-chain 来更改配置，它本身就是在你的配置项的基础上作修改的，所以你的配置里没有被改到的地方都会被保留。更具体的 webpack-chain 用法可查阅 https://github.com/mozilla-neutrino/webpack-chain
另外这个仓库只做翻译讨论，将来有类似的问题请在主流的问答社区或论坛发起讨论
谢谢
