### ISSUE TITLE
error when create a project

### ISSUE THREAD

**Issue by comeonjin** [vuejs/vue-docs-zh-cn#11]
npm ERR! Unexpected end of JSON input while parsing near '...n-node-resolve":"^2.0'
 ERROR  command failed: npm install --loglevel error --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist
ps:  Vue CLI v3.0.0-beta.16

**Comment by Jinjiang** [comment]
这个仓库只做翻译讨论，使用问题请在主流的问答社区或论坛讨论，bug 可以直接提给相应的库的 repo。
谢谢
