### ISSUE TITLE
怎么查看webpack  配置

### ISSUE THREAD

**Issue by wenJonSnow** [vuejs/vue-docs-zh-cn#13]
npm install -g @ vue / cli  , vue creat vueApp 这2个命令生成的项目 如何查看 webpack 配置，因为没有build 和config 文件。

**Comment by hiYoHoo** [comment]
可以在项目根目录下新建 vue.config.js 文件，参考这里：https://cli.vuejs.org/config/

**Comment by LDWX** [comment]
使用 vue inpsect > output.js 可以将webpack配置打印到output.js文件中进行查看

**Comment by Jinjiang** [comment]
几位好，这个仓库只会讨论一些零散的非正式的中文文档翻译，不讨论技术本身。
cli 的技术问题反馈请移步至：https://github.com/vuejs/vue-cli 或其它技术论坛和问答社区。这些地方有更多更活跃的人可以帮到大家。
更何况 cli 的中文文档也已经“转正”了：https://cli.vuejs.org/
因此这里对该 issue 做关闭处理。
感谢理解
