### ISSUE TITLE
请问如何在 cli@3.0.0 中使用 webpack-bundle-analyzer

### ISSUE THREAD

**Issue by zzlw** [vuejs/vue-docs-zh-cn#15]

**Comment by Jinjiang** [comment]
几位好，这个仓库只会讨论一些零散的非正式的中文文档翻译，不讨论技术本身。
cli 的技术问题反馈请移步至：https://github.com/vuejs/vue-cli 或其它技术论坛和问答社区。这些地方有更多更活跃的人可以帮到大家。
更何况 cli 的中文文档也已经“转正”了：https://cli.vuejs.org/
因此这里对该 issue 做关闭处理。
感谢理解
