### ISSUE TITLE
在已有项目中 vue add typescript 报错

### ISSUE THREAD

**Issue by tinaawang** [vuejs/vue-docs-zh-cn#28]
![image](https://user-images.githubusercontent.com/32811977/69595148-aecbe600-1039-11ea-9b2a-c972640c85fc.png)
 Error: Cannot find module '@vue/cli-plugin-router/generator/template/src/views/Home.vue' from 'D:\admin\node_modules\@vue\cli-plugin-typescript\generator\template\src\views

**Comment by Randysheng** [comment]
> ![image](https://user-images.githubusercontent.com/32811977/69595148-aecbe600-1039-11ea-9b2a-c972640c85fc.png)
> Error: Cannot find module '@vue/cli-plugin-router/generator/template/src/views/Home.vue' from 'D:\admin\node_modules@vue\cli-plugin-typescript\generator\template\src\views

我使用版本为 3.8.4 的 `vue-cli` 时，也遇到了这个问题。
然后将 `vue-cli` 升级到最新版，执行 `vue add typescript`，没有错误了。希望你已经解决了

**Comment by Jinjiang** [comment]
cc @sodatea

**Comment by sodatea** [comment]
嗯这是当时的版本问题，现在应该好了。
