### ISSUE TITLE
vue add @vue/unit-mocha 报错，无法下载

### ISSUE THREAD

**Issue by 5201314999** [vuejs/vue-docs-zh-cn#31]
在已有的vue-cli4 @vue/cli 4.2.3 创建的项目中打算引入 mocha ，同时支持es6 语法import ，mocha 默认是node 语法的， 试了很多次都失败

**Comment by sodatea** [comment]
无法下载可能是网络问题。
如需进一步帮助，请使用 issue helper 提问并提供更为完整的错误信息 https://new-issue.vuejs.org/?repo=vuejs/vue-cli&lang=zh-cn
