### ISSUE TITLE
vue add @vue/typescript 也报错了。。。

### ISSUE THREAD

**Issue by 845056166** [vuejs/vue-docs-zh-cn#34]
![image](https://user-images.githubusercontent.com/20857573/97954114-9170d180-1ddd-11eb-8d0a-74d75f9a6bf0.png)

vue 的版本:4.5.7
![image](https://user-images.githubusercontent.com/20857573/97954133-a3eb0b00-1ddd-11eb-9d24-8309d3d7090c.png)
可以帮我看看嘛，不知道是什么原因😭

**Comment by haoqunjiang** [comment]
```
vue config --set packageManager npm
```

原因是你曾经选择过使用 yarn 作为包管理器，后来 yarn 被卸载了但是 Vue CLI 设置并没有被改回来。

**Comment by 845056166** [comment]
知道了，感谢大佬
