### ISSUE TITLE
V3版本生命周期图不清晰，无法正常查看

### ISSUE THREAD

**Issue by qbob** [vuejs/vue-docs-zh-cn#37]
V3版本生命周期图打开加载慢，文字锯齿严重，无法正常查看。v2正常
系统：macOs
环境：  Google Chrome 版本 88.0.4324.96（正式版本） (x86_64)
![image](https://user-images.githubusercontent.com/1908445/108791122-4ad7fa80-75b9-11eb-8563-914df8dd5db3.png)

**Comment by Justineo** [comment]
目测是网速原因导致图片没有加载完，我这边看到图片内容是正常的。

**Comment by qbob** [comment]
> 目测是网速原因导致图片没有加载完，我这边看到图片内容是正常的。

同样的网速，vue2文档中的生命周期图片加载正常

**Comment by haoqunjiang** [comment]
Vue 3 版本的中文文档部署在 Netlify，和 cn.vuejs.org 不一样。出现这个状况不意外。
