### ISSUE TITLE
npm run test:e2e 报错，求大佬指点

### ISSUE THREAD

**Issue by Jam1zhu** [vuejs/vue-docs-zh-cn#38]
脚手架生成的项目，选择了`cypress`，运行`npm run test:e2e`，能出来gui页面，点击自动生成的test.js，运行报错，并自动关闭gui
```
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
 {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
```
系统：windows 64
nodejs：v12.20.1
npm：7.5.6

上网查找说降低node版本可以解决这个问题，切换成`8.12.0`，依旧有这个问题

**Comment by haoqunjiang** [comment]
可能是代理设置问题。也可能是 Cypress 版本问题。
先检查一下命令行环境里是不是有什么 `HTTP_PROXY` 之类的环境变量。其次试着升级一下 Cypress（直接在项目里 `npm install -D cypress` 就行）

如果还需要进一步帮助，请使用 issue helper 提问并提供更为完整的错误信息 https://new-issue.vuejs.org/?repo=vuejs/vue-cli&lang=zh-cn
