### ISSUE TITLE
ubuntu 下用vue-cli 创建项目时，rename 命令提示权限不足

### ISSUE THREAD

**Issue by dahuzix** [vuejs/vue-docs-zh-cn#9]
ubuntu 下用vue-cli 创建项目时，rename 命令提示权限不足

执行的具体命令是

sudo vue create my-project
命令运行之后：
1.creating project in  /media/vmshared/www/my-project
2.initialing git repository  ..
3.installing cli plugins
在安装插件过程中，有一句命令报错 提示权限不足

具体的报错语句是 rename  ,operation not permitted.
这是权限不足吗，可是我用的是 sudo 执行，请问怎么处理

**Comment by Jinjiang** [comment]
比较难判断，建议去主流的问答社区问问看，这里只讨论文档翻译问题
谢谢
